project:
  type: website
  output-dir: C:\Users\sadiejsr.stu\OneDrive - UBC\Documents\GitHub\E-Portfolio

website:
  title: "Sadie Russell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: project.qmd
        text: Projects
      - href: content.qmd
        text: Content & Deliverables
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

