project:
  type: website
  output-dir: C:\Users\sadiejsr.stu\OneDrive - UBC\Documents\GitHub\E-Portfolio

website:
  title: "Sadie Russell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: project.qmd
        text: Projects
      - href: coding.qmd
        text: Skills
        
      - href: fieldworkgallery.qmd
        text: Field Work Gallery


format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

