---
title: "Resume"
---

# Education

**Master of Geomatics for Environmental Management**, University of British Columbia, 2025

Thesis: “Investigation of the Influence of Aspen Serpentine Lead Miner (Phyllocnistis populiella) on Fire Severity In Trembling Aspen (Populus tremuloides) Dominant Stands in Northeastern British Columbia”

Supervisor: Dr. Allan Carroll

**First Class Honours Bachelor of Science in Environmental Science and Statistics**, Dalhousie University, 2024

Thesis: “Halifax Residential Air Quality; Public Perception and PM2.5 Concentrations” Supervisor: Dr. Daniel Rainham Certificate: Environmental Impact Assessment

# Professional Experience

**Graduate Research Assistant, University of British Columbia, 2024-2025**

\- Developed methods for assessing undergraduate learning outcomes

\- Organized and orchestrated 2-day experiment for 130 participants

\- Analyzed results using Rstudio

**Writer/Editor, The Discovery Centre, Halifax, NS, 2022**

\- Five-month internship through Dalhousie University

\- Developed five educational packages on climate change for Nova Scotian schools

\- Conducted interviews with lead researchers from MEOPAR projects

\- Created and led four workshops for kids aged 8 to 12 to test education packages

# Publications

*Reports*

Discover Our Climate, MEOPAR and The Discovery Centre, 2023, https://thediscoverycentre.ca/discover-our-climate-decouverte-de-notre-climat/

# Conferences & Talks

*Conference Presentations*

**S.J. Russell**, 2024, “Halifax Residential Air Quality: Public Perceptions and PM2.5 Concentrations” Science Atlantic Environment Conference, UPEI, Charlottetown, PEI

# Teaching Assistantships

**Facilitated tutorial sessions and held office hours for the following undergraduate courses:**

**University of British Columbia**

Conservation Science and Sustainability (Winter 2 Term, 2025), 3 credits, 139 students

**Dalhousie University**

Current Environmental Challenges (Winter Term, 2024), 3 credits, 124 students Foundations of Environmental Science (Fall Term, 2023), 3 credits, 119 students Environmental Analytics (Fall Term, 2023), 3 credits, 79 students

**Instructed and supervised fieldwork in the following undergraduate course:**

**Dalhousie University**

Field Methods in Environmental Science (Summer 1 Term, 2024), 3 credits, 24 students

# Institutional Service

Aquatic Field Technician, Project Watershed/Nature Vancouver, 2024-2025
